services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pos-sqlserver-dev
    environment:
      SA_PASSWORD: "DevPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_dev_data:/var/opt/mssql
    networks:
      - pos-dev-network
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "DevPassword123!" -C -Q "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  sqlserver_dev_data:
    driver: local

networks:
  pos-dev-network:
    driver: bridge
